# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fee8c2500a6135d0a2e10a2bd19db2424ea0f577ba88719d6bf674383794171775c66138ae302007b597c5b1d2c8a66ccd1a5993cceb49e3774af1ed6092b60

test:
  secret_key_base: f492d3b75dfcbe79dccdef014a7f0d874d8a3526810e6f8b371696121bc9a6f8c579ce0a939e3bbc213de47427f7ec4c28a479ac2ee74988b6a54ffeebe4de99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
